// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * Body_chat_with_files_endpoint_chat__thread_id__with_files_post
 */
export type BodyChatWithFilesEndpointChatThreadIdWithFilesPost = {
    /**
     * Messages
     *
     * JSON 字符串，形如 {"messages": [{"role":"user","content":"..."}]}
     */
    messages: string;
    /**
     * Files
     *
     * PDF / DOCX 文件列表
     */
    files?: Array<Blob | File>;
};

/**
 * Body_chat_with_files_stream_endpoint_chat__thread_id__with_files_stream_post
 */
export type BodyChatWithFilesStreamEndpointChatThreadIdWithFilesStreamPost = {
    /**
     * Messages
     *
     * JSON 字符串，形如 {"messages": [{"role":"user","content":"..."}]}
     */
    messages: string;
    /**
     * Files
     *
     * PDF / DOCX 文件列表
     */
    files?: Array<Blob | File>;
};

/**
 * Body_process_upload_endpoint_api_rag_process_upload_post
 */
export type BodyProcessUploadEndpointApiRagProcessUploadPost = {
    /**
     * Files
     *
     * 待处理的 .md 文件，支持批量上传
     */
    files: Array<Blob | File>;
};

/**
 * Body_upload_file_endpoint_api_files_upload_post
 */
export type BodyUploadFileEndpointApiFilesUploadPost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * Body_upload_file_endpoint_settings_memory_and_skill_upload_post
 */
export type BodyUploadFileEndpointSettingsMemoryAndSkillUploadPost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * ChatRequest
 *
 * 聊天请求
 */
export type ChatRequest = {
    /**
     * Messages
     *
     * 对话消息列表
     */
    messages: Array<Message>;
    /**
     * Checkpoint Id
     *
     * 检查点 ID，用于从指定检查点恢复/重放
     */
    checkpoint_id?: string | null;
    /**
     * Checkpoint Ns
     *
     * 检查点命名空间（子图场景）
     */
    checkpoint_ns?: string | null;
    /**
     * Rubric
     *
     * 完成条件（rubric）。设定后 Agent 自然停止时由独立评估器判断是否满足，未满足则自动注入反馈继续循环，直到满足或达到迭代上限
     */
    rubric?: string | null;
};

/**
 * ChatResponse
 *
 * 聊天响应
 */
export type ChatResponse = {
    /**
     * Messages
     */
    messages: Array<MessageResponse>;
};

/**
 * CheckpointHistoryResponse
 *
 * 检查点历史列表（支持分页）
 */
export type CheckpointHistoryResponse = {
    /**
     * Thread Id
     */
    thread_id: string;
    /**
     * Checkpoints
     */
    checkpoints: Array<CheckpointSummary>;
};

/**
 * CheckpointSummary
 *
 * 检查点摘要 — 时间线侧边栏中的每个条目。
 *
 * parent_checkpoint_id 来自 LangGraph state.parent_config，
 * 表示线性执行链中的前一个检查点。同 parent 的子节点为兄弟分支。
 */
export type CheckpointSummary = {
    /**
     * Config
     *
     * 完整 config {configurable: {thread_id, checkpoint_id, checkpoint_ns}}，可直接用于 replay/fork
     */
    config?: {
        [key: string]: unknown;
    };
    /**
     * Next Nodes
     *
     * 接下来将执行的节点列表（为空表示已完成）
     */
    next_nodes?: Array<string>;
    /**
     * Input Preview
     *
     * 用户输入内容的前 80 字预览
     */
    input_preview?: string | null;
    /**
     * Parent Checkpoint Id
     *
     * 父检查点 ID（根节点为 None）。前端按此字段分组得到兄弟分支
     */
    parent_checkpoint_id?: string | null;
    /**
     * Source
     *
     * 检查点来源：input / loop / fork。前端据此标注 原始/重试/分支
     */
    source?: string;
    /**
     * Leaf Checkpoint Id
     *
     * 该 input 所在分支的叶子检查点 ID，用于分支切换时加载完整历史。None 表示尚未计算或分支未完成。
     */
    leaf_checkpoint_id?: string | null;
};

/**
 * ChunkDetail
 *
 * 单个 chunk 的详细信息。
 */
export type ChunkDetail = {
    /**
     * Index
     *
     * 分块序号，从 1 开始
     */
    index: number;
    /**
     * Content Length
     *
     * 该 chunk 的字符数
     */
    content_length: number;
    /**
     * Preview
     *
     * 前 120 个字符的摘要预览
     */
    preview: string;
    /**
     * Header Path
     *
     * 该 chunk 所属的标题路径，如 '# 概述 > ## 背景'
     */
    header_path?: string | null;
    /**
     * Is Char Split
     *
     * 是否经过二级字符切分（true 表示该 chunk 来自字符级再分块）
     */
    is_char_split?: boolean;
};

/**
 * ClearCollectionResponse
 *
 * 清空集合响应。
 */
export type ClearCollectionResponse = {
    /**
     * Deleted Count
     *
     * 清除的文档数
     */
    deleted_count: number;
    /**
     * Collection Name
     *
     * 集合名称
     */
    collection_name: string;
    /**
     * Message
     *
     * 操作描述
     */
    message?: string;
};

/**
 * CollectionDocument
 *
 * 集合中的单条文档。
 */
export type CollectionDocument = {
    /**
     * Id
     *
     * 文档 ID
     */
    id: string;
    /**
     * Document
     *
     * 文档内容
     */
    document?: string | null;
    /**
     * Metadata
     *
     * 元数据键值对
     */
    metadata?: {
        [key: string]: unknown;
    } | null;
};

/**
 * CollectionDocumentsResponse
 *
 * 分页文档响应。
 */
export type CollectionDocumentsResponse = {
    /**
     * Collection Name
     *
     * 集合名称
     */
    collection_name: string;
    /**
     * Page
     *
     * 当前页码
     */
    page: number;
    /**
     * Page Size
     *
     * 每页条数
     */
    page_size: number;
    /**
     * Total
     *
     * 总文档数
     */
    total: number;
    /**
     * Documents
     *
     * 当前页文档列表
     */
    documents?: Array<CollectionDocument>;
};

/**
 * CollectionInfo
 *
 * 集合基本信息。
 */
export type CollectionInfo = {
    /**
     * Name
     *
     * 集合名称
     */
    name: string;
    /**
     * Count
     *
     * 文档数量
     */
    count: number;
};

/**
 * CollectionListResponse
 *
 * 所有集合列表。
 */
export type CollectionListResponse = {
    /**
     * Collections
     *
     * 集合列表
     */
    collections?: Array<CollectionInfo>;
};

/**
 * CollectionStatsResponse
 *
 * 集合统计数据。
 */
export type CollectionStatsResponse = {
    /**
     * Collection Name
     *
     * 集合名称
     */
    collection_name: string;
    /**
     * Total Count
     *
     * 总文档数
     */
    total_count: number;
    /**
     * Sampled Count
     *
     * 实际采样数（可能小于 total_count）
     */
    sampled_count: number;
    /**
     * Non Empty Count
     *
     * 非空文档数
     */
    non_empty_count: number;
    /**
     * Empty Count
     *
     * 空文档数
     */
    empty_count: number;
    /**
     * Empty Rate
     *
     * 文档非空率（百分比）
     */
    empty_rate: string;
    /**
     * Avg Doc Length
     *
     * 平均文档长度（字符数）
     */
    avg_doc_length: number;
    /**
     * Vector Dimension
     *
     * 向量维度
     */
    vector_dimension?: number | null;
    /**
     * Metadata Coverage
     *
     * 元数据字段覆盖率列表
     */
    metadata_coverage?: Array<{
        [key: string]: unknown;
    }>;
};

/**
 * CreateDirectoryRequest
 *
 * 创建目录请求
 */
export type CreateDirectoryRequest = {
    /**
     * Path
     *
     * 相对路径
     */
    path: string;
};

/**
 * CreateFileRequest
 *
 * 创建文件请求
 */
export type CreateFileRequest = {
    /**
     * Path
     *
     * 相对路径（含文件名）
     */
    path: string;
    /**
     * Content
     *
     * 文件内容，为空则创建空文件
     */
    content?: string;
};

/**
 * Decision
 *
 * 单条决策
 */
export type Decision = {
    /**
     * Type
     *
     * 决策类型
     */
    type: 'approve' | 'reject' | 'edit';
    /**
     * Edited Action
     *
     * 编辑后的动作（type=edit 时）
     */
    edited_action?: {
        [key: string]: unknown;
    } | null;
};

/**
 * DeleteCollectionResponse
 *
 * 删除集合响应。
 */
export type DeleteCollectionResponse = {
    /**
     * Collection Name
     *
     * 已删除的集合名称
     */
    collection_name: string;
    /**
     * Message
     *
     * 操作描述
     */
    message?: string;
};

/**
 * DeleteDocsRequest
 *
 * 批量删除文档请求。
 */
export type DeleteDocsRequest = {
    /**
     * Ids
     *
     * 待删除的文档 ID 列表
     */
    ids: Array<string>;
};

/**
 * DeleteDocsResponse
 *
 * 批量删除文档响应。
 */
export type DeleteDocsResponse = {
    /**
     * Deleted Count
     *
     * 成功删除的文档数
     */
    deleted_count: number;
    /**
     * Message
     *
     * 操作描述
     */
    message?: string;
};

/**
 * DeleteRequest
 *
 * 删除文件/目录请求
 */
export type DeleteRequest = {
    /**
     * Path
     *
     * 要删除的文件/目录相对路径
     */
    path: string;
};

/**
 * ForkRequest
 *
 * 分支出请求 — 从检查点分叉，可同时修改状态后继续执行。
 *
 * 后端先调用 graph.update_state(config, values={.}) 创建新分支检查点，
 * 再调用 graph.invoke(None, fork_config) 继续执行。
 *
 * 关键语义：
 * - update_state 不修改原线程历史；原始执行链完整保留
 * - 新分支从指定检查点独立发展，前端应展示为对话树
 * - values 可传入任意 state 字段（如 messages、自定义字段），通过对应 reducer 应用
 * - 遇到中断时总是重新触发
 * - as_node 在并行分支 / 跳过节点 / 新线程场景下显式指定
 */
export type ForkRequest = {
    /**
     * Thread Id
     *
     * 对话线程 ID
     */
    thread_id: string;
    /**
     * Checkpoint Id
     *
     * 分支出起点检查点 ID
     */
    checkpoint_id: string;
    /**
     * Checkpoint Ns
     *
     * 检查点命名空间（子图场景）
     */
    checkpoint_ns?: string;
    /**
     * Values
     *
     * 要修改的 state 字段。如 {'messages': [.]} 或 {'topic': 'new'}。空 dict 表示仅创建分支引用
     */
    values?: {
        [key: string]: unknown;
    };
    /**
     * As Node
     *
     * 显式指定产生此更新的节点名（并行分支 / 跳过节点 / 新线程场景）
     */
    as_node?: string | null;
    /**
     * Stream
     *
     * True 时通过 SSE 流式返回
     */
    stream?: boolean;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Message
 *
 * 单个消息模型
 */
export type Message = {
    /**
     * Role
     *
     * 消息发送者角色
     */
    role: 'user' | 'assistant' | 'system';
    /**
     * Content
     *
     * 消息内容：纯文本字符串或多模态 content blocks 列表
     */
    content: string | Array<{
        [key: string]: unknown;
    }>;
};

/**
 * MessageResponse
 *
 * 单条消息响应
 */
export type MessageResponse = {
    /**
     * Role
     */
    role: string;
    /**
     * Content
     */
    content?: string | Array<{
        [key: string]: unknown;
    }>;
    /**
     * Reason Content
     */
    reason_content?: string | null;
};

/**
 * ModifyFileRequest
 *
 * 修改文件内容请求
 */
export type ModifyFileRequest = {
    /**
     * Path
     *
     * 文件相对路径
     */
    path: string;
    /**
     * Content
     *
     * 新的文件内容
     */
    content: string;
};

/**
 * MoveRequest
 *
 * 移动文件/目录请求
 */
export type MoveRequest = {
    /**
     * Path
     *
     * 当前相对路径
     */
    path: string;
    /**
     * Target Dir
     *
     * 目标目录相对路径，空字符串表示根目录
     */
    target_dir: string;
};

/**
 * RAGDeleteRequest
 *
 * 从向量库删除文档的请求。
 */
export type RagDeleteRequest = {
    /**
     * Ids
     *
     * 待删除的文档 ID 列表（可从向量库查询获取）
     */
    ids: Array<string>;
};

/**
 * RAGDeleteResponse
 *
 * 删除操作响应。
 */
export type RagDeleteResponse = {
    /**
     * Deleted Count
     *
     * 成功删除的文档数
     */
    deleted_count: number;
    /**
     * Collection Count
     *
     * 向量库当前文档块总数
     */
    collection_count: number;
    /**
     * Message
     *
     * 操作描述
     */
    message?: string;
};

/**
 * RAGEmbeddingConfig
 *
 * 嵌入模型配置。
 */
export type RagEmbeddingConfig = {
    /**
     * Model
     *
     * Ollama 嵌入模型名称
     */
    model?: string;
    /**
     * Base Url
     *
     * Ollama 服务地址
     */
    base_url?: string;
};

/**
 * RAGFullConfigModel
 *
 * 完整的 rag_config.yaml 结构 —— 读/写共用。
 */
export type RagFullConfigModel = {
    embedding?: RagEmbeddingConfig;
    rag?: RagPipelineSection;
};

/**
 * RAGHNSWConfig
 *
 * Chroma HNSW 索引参数。
 */
export type RaghnswConfig = {
    /**
     * Space
     *
     * 距离度量: cosine / l2 / ip
     */
    space?: string;
    /**
     * Ef Construction
     *
     * 构建时的搜索深度
     */
    ef_construction?: number;
    /**
     * Max Neighbors
     *
     * 最大邻居数
     */
    max_neighbors?: number;
    /**
     * Ef Search
     *
     * 查询时的搜索深度
     */
    ef_search?: number;
    /**
     * Num Threads
     *
     * 构建时的线程数
     */
    num_threads?: number;
    /**
     * Batch Size
     *
     * 批量入库大小
     */
    batch_size?: number;
    /**
     * Sync Threshold
     *
     * 同步阈值
     */
    sync_threshold?: number;
    /**
     * Resize Factor
     *
     * 扩容因子
     */
    resize_factor?: number;
};

/**
 * RAGHealthResponse
 *
 * 向量库健康检查响应。
 */
export type RagHealthResponse = {
    /**
     * Collection Name
     *
     * 集合名称
     */
    collection_name: string;
    /**
     * Collection Count
     *
     * 当前文档块总数
     */
    collection_count: number;
    /**
     * Persist Directory
     *
     * 持久化目录
     */
    persist_directory: string;
    /**
     * Embedding Model
     *
     * 嵌入模型名称
     */
    embedding_model: string;
    /**
     * Embedding Base Url
     *
     * 嵌入模型服务地址
     */
    embedding_base_url: string;
};

/**
 * RAGPipelineSection
 *
 * rag_config.yaml 中 rag 段的配置。
 */
export type RagPipelineSection = {
    splitter?: RagSplitterConfig;
    hnsw?: RaghnswConfig;
    processing?: RagProcessingConfig;
};

/**
 * RAGProcessRequest
 *
 * 处理 markdown 文件并存入向量库的请求（本地路径模式，保留兼容）。
 */
export type RagProcessRequest = {
    /**
     * Files
     *
     * 待处理的 .md 文件绝对路径列表
     */
    files: Array<string>;
    /**
     * Preview Dir
     *
     * 分块预览输出目录，不传则使用配置中的默认值
     */
    preview_dir?: string | null;
    /**
     * Preview Only
     *
     * 仅预览分块而不入库（true 时只切分不保存）
     */
    preview_only?: boolean;
};

/**
 * RAGProcessResponse
 *
 * 批量处理响应。
 */
export type RagProcessResponse = {
    /**
     * Total Files
     *
     * 总文件数
     */
    total_files: number;
    /**
     * Success Count
     *
     * 成功数
     */
    success_count: number;
    /**
     * Failed Count
     *
     * 失败数
     */
    failed_count: number;
    /**
     * Total Chunks
     *
     * 总入库分块数
     */
    total_chunks: number;
    /**
     * Collection Count
     *
     * 向量库当前文档块总数
     */
    collection_count: number;
    /**
     * 本次处理使用的分割配置
     */
    split_config: SplitConfig;
    /**
     * Results
     *
     * 每个文件的处理详情
     */
    results?: Array<RagProcessResult>;
};

/**
 * RAGProcessResult
 *
 * 单个文件的处理结果。
 */
export type RagProcessResult = {
    /**
     * Filename
     *
     * 文件名
     */
    filename: string;
    /**
     * File Size
     *
     * 原文件大小（字节）
     */
    file_size: number;
    /**
     * Chunks Count
     *
     * 生成的分块数
     */
    chunks_count: number;
    /**
     * Status
     *
     * 处理状态: success / error
     */
    status?: string;
    /**
     * Error
     *
     * 失败时的错误信息
     */
    error?: string | null;
    /**
     * Chunks
     *
     * 每个 chunk 的详细信息（包含大小、标题路径等）
     */
    chunks?: Array<ChunkDetail>;
};

/**
 * RAGProcessingConfig
 *
 * 处理参数配置。
 */
export type RagProcessingConfig = {
    /**
     * Preview Output Dir
     *
     * 分块预览输出目录
     */
    preview_output_dir?: string;
    /**
     * Enable Interactive
     *
     * CLI 模式下是否交互确认
     */
    enable_interactive?: boolean;
};

/**
 * RAGSplitterConfig
 *
 * 文档分割器配置。
 */
export type RagSplitterConfig = {
    /**
     * Headers
     *
     * 用于切分的标题层级
     */
    headers?: Array<string>;
    /**
     * Return Each Line
     *
     * 是否逐行返回
     */
    return_each_line?: boolean;
    /**
     * Strip Headers
     *
     * 是否剥离标题行
     */
    strip_headers?: boolean;
    /**
     * Enable Char Split
     *
     * 是否启用二级字符切分
     */
    enable_char_split?: boolean;
    /**
     * Chunk Size
     *
     * 字符切分最大 chunk 大小
     */
    chunk_size?: number;
    /**
     * Chunk Overlap
     *
     * 字符切分重叠区间大小
     */
    chunk_overlap?: number;
};

/**
 * RenameRequest
 *
 * 重命名文件/目录请求
 */
export type RenameRequest = {
    /**
     * Path
     *
     * 当前相对路径
     */
    path: string;
    /**
     * New Name
     *
     * 新名称（仅文件名/目录名，不含路径）
     */
    new_name: string;
};

/**
 * ReplayRequest
 *
 * 重放请求 — 从指定检查点恢复执行。
 *
 * 后端调用 graph.invoke(None, config) 从该检查点重新执行后续节点：
 * - 检查点之前的节点：不重新执行（结果已缓存）
 * - 检查点之后的节点：重新执行（LLM / API / 中断会再次触发，结果可能不同）
 * - 从最终检查点（next 为空）重放：无操作
 * - 提供 messages 时：注入用户消息作为新输入，触发模型重新生成
 */
export type ReplayRequest = {
    /**
     * Thread Id
     *
     * 对话线程 ID
     */
    thread_id: string;
    /**
     * Checkpoint Id
     *
     * 目标检查点 ID
     */
    checkpoint_id: string;
    /**
     * Checkpoint Ns
     *
     * 检查点命名空间（子图场景）
     */
    checkpoint_ns?: string;
    /**
     * Messages
     *
     * 要注入的用户消息列表，格式 [{'role':'user','content':'.'}]
     */
    messages?: Array<{
        [key: string]: unknown;
    }> | null;
    /**
     * Stream
     *
     * True 时通过 SSE (text/event-stream) 流式返回
     */
    stream?: boolean;
};

/**
 * ResumeRequest
 *
 * 中断恢复请求
 */
export type ResumeRequest = {
    /**
     * Decisions
     *
     * 用户决策列表
     */
    decisions: Array<Decision>;
};

/**
 * SkillsUpdateRequest
 *
 * Skills 开关更新请求。
 */
export type SkillsUpdateRequest = {
    /**
     * Enabled
     */
    enabled: Array<string>;
};

/**
 * SplitConfig
 *
 * 当前生效的文档分割配置。
 */
export type SplitConfig = {
    /**
     * Headers
     *
     * 用于切分的标题层级，如 ['#', '##', '###']
     */
    headers: Array<string>;
    /**
     * Return Each Line
     *
     * 是否逐行返回
     */
    return_each_line?: boolean;
    /**
     * Strip Headers
     *
     * 是否剥离标题行
     */
    strip_headers?: boolean;
    /**
     * Enable Char Split
     *
     * 是否启用二级字符切分
     */
    enable_char_split?: boolean;
    /**
     * Chunk Size
     *
     * 字符切分的最大 chunk 大小（字符数）
     */
    chunk_size: number;
    /**
     * Chunk Overlap
     *
     * 字符切分的重叠区间大小（字符数）
     */
    chunk_overlap: number;
    /**
     * Secondary Separators
     *
     * 二级字符切分的分隔符优先级
     */
    secondary_separators?: Array<string>;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type ChatEndpointChatThreadIdPostData = {
    body: ChatRequest;
    path: {
        /**
         * Thread Id
         */
        thread_id: string;
    };
    query?: never;
    url: '/chat/{thread_id}';
};

export type ChatEndpointChatThreadIdPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChatEndpointChatThreadIdPostError = ChatEndpointChatThreadIdPostErrors[keyof ChatEndpointChatThreadIdPostErrors];

export type ChatEndpointChatThreadIdPostResponses = {
    /**
     * Successful Response
     */
    200: ChatResponse;
};

export type ChatEndpointChatThreadIdPostResponse = ChatEndpointChatThreadIdPostResponses[keyof ChatEndpointChatThreadIdPostResponses];

export type ChatStreamChatThreadIdStreamPostData = {
    body: ChatRequest;
    path: {
        /**
         * Thread Id
         */
        thread_id: string;
    };
    query?: never;
    url: '/chat/{thread_id}/stream';
};

export type ChatStreamChatThreadIdStreamPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChatStreamChatThreadIdStreamPostError = ChatStreamChatThreadIdStreamPostErrors[keyof ChatStreamChatThreadIdStreamPostErrors];

export type ChatStreamChatThreadIdStreamPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ResumeChatEndpointChatThreadIdResumePostData = {
    body: ResumeRequest;
    path: {
        /**
         * Thread Id
         */
        thread_id: string;
    };
    query?: never;
    url: '/chat/{thread_id}/resume';
};

export type ResumeChatEndpointChatThreadIdResumePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResumeChatEndpointChatThreadIdResumePostError = ResumeChatEndpointChatThreadIdResumePostErrors[keyof ResumeChatEndpointChatThreadIdResumePostErrors];

export type ResumeChatEndpointChatThreadIdResumePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ChatWithFilesEndpointChatThreadIdWithFilesPostData = {
    body: BodyChatWithFilesEndpointChatThreadIdWithFilesPost;
    path: {
        /**
         * Thread Id
         */
        thread_id: string;
    };
    query?: never;
    url: '/chat/{thread_id}/with-files';
};

export type ChatWithFilesEndpointChatThreadIdWithFilesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChatWithFilesEndpointChatThreadIdWithFilesPostError = ChatWithFilesEndpointChatThreadIdWithFilesPostErrors[keyof ChatWithFilesEndpointChatThreadIdWithFilesPostErrors];

export type ChatWithFilesEndpointChatThreadIdWithFilesPostResponses = {
    /**
     * Successful Response
     */
    200: ChatResponse;
};

export type ChatWithFilesEndpointChatThreadIdWithFilesPostResponse = ChatWithFilesEndpointChatThreadIdWithFilesPostResponses[keyof ChatWithFilesEndpointChatThreadIdWithFilesPostResponses];

export type ChatWithFilesStreamEndpointChatThreadIdWithFilesStreamPostData = {
    body: BodyChatWithFilesStreamEndpointChatThreadIdWithFilesStreamPost;
    path: {
        /**
         * Thread Id
         */
        thread_id: string;
    };
    query?: never;
    url: '/chat/{thread_id}/with-files/stream';
};

export type ChatWithFilesStreamEndpointChatThreadIdWithFilesStreamPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChatWithFilesStreamEndpointChatThreadIdWithFilesStreamPostError = ChatWithFilesStreamEndpointChatThreadIdWithFilesStreamPostErrors[keyof ChatWithFilesStreamEndpointChatThreadIdWithFilesStreamPostErrors];

export type ChatWithFilesStreamEndpointChatThreadIdWithFilesStreamPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetMessagesHistoryChatThreadIdGetMessagesHistoryGetData = {
    body?: never;
    path: {
        /**
         * Thread Id
         */
        thread_id: string;
    };
    query?: {
        /**
         * Checkpoint Id
         *
         * 可选，指定检查点 ID 以获取对应分支的消息
         */
        checkpoint_id?: string | null;
    };
    url: '/chat/{thread_id}/get-messages-history';
};

export type GetMessagesHistoryChatThreadIdGetMessagesHistoryGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMessagesHistoryChatThreadIdGetMessagesHistoryGetError = GetMessagesHistoryChatThreadIdGetMessagesHistoryGetErrors[keyof GetMessagesHistoryChatThreadIdGetMessagesHistoryGetErrors];

export type GetMessagesHistoryChatThreadIdGetMessagesHistoryGetResponses = {
    /**
     * Successful Response
     */
    200: ChatResponse;
};

export type GetMessagesHistoryChatThreadIdGetMessagesHistoryGetResponse = GetMessagesHistoryChatThreadIdGetMessagesHistoryGetResponses[keyof GetMessagesHistoryChatThreadIdGetMessagesHistoryGetResponses];

export type DeleteMessagesHistoryChatThreadIdDeleteMessagesHistoryDeleteData = {
    body?: never;
    path: {
        /**
         * Thread Id
         */
        thread_id: string;
    };
    query?: never;
    url: '/chat/{thread_id}/delete-messages-history';
};

export type DeleteMessagesHistoryChatThreadIdDeleteMessagesHistoryDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteMessagesHistoryChatThreadIdDeleteMessagesHistoryDeleteError = DeleteMessagesHistoryChatThreadIdDeleteMessagesHistoryDeleteErrors[keyof DeleteMessagesHistoryChatThreadIdDeleteMessagesHistoryDeleteErrors];

export type DeleteMessagesHistoryChatThreadIdDeleteMessagesHistoryDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListThreadsEndpointThreadsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/threads';
};

export type ListThreadsEndpointThreadsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetInputCheckpointsCheckpointsThreadIdInputsGetData = {
    body?: never;
    path: {
        /**
         * Thread Id
         */
        thread_id: string;
    };
    query?: {
        /**
         * Limit
         *
         * 每页数量
         */
        limit?: number;
        /**
         * Offset
         *
         * 偏移量
         */
        offset?: number;
    };
    url: '/checkpoints/{thread_id}/inputs';
};

export type GetInputCheckpointsCheckpointsThreadIdInputsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetInputCheckpointsCheckpointsThreadIdInputsGetError = GetInputCheckpointsCheckpointsThreadIdInputsGetErrors[keyof GetInputCheckpointsCheckpointsThreadIdInputsGetErrors];

export type GetInputCheckpointsCheckpointsThreadIdInputsGetResponses = {
    /**
     * Successful Response
     */
    200: CheckpointHistoryResponse;
};

export type GetInputCheckpointsCheckpointsThreadIdInputsGetResponse = GetInputCheckpointsCheckpointsThreadIdInputsGetResponses[keyof GetInputCheckpointsCheckpointsThreadIdInputsGetResponses];

export type ReplayCheckpointCheckpointsThreadIdReplayPostData = {
    body: ReplayRequest;
    path: {
        /**
         * Thread Id
         */
        thread_id: string;
    };
    query?: never;
    url: '/checkpoints/{thread_id}/replay';
};

export type ReplayCheckpointCheckpointsThreadIdReplayPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReplayCheckpointCheckpointsThreadIdReplayPostError = ReplayCheckpointCheckpointsThreadIdReplayPostErrors[keyof ReplayCheckpointCheckpointsThreadIdReplayPostErrors];

export type ReplayCheckpointCheckpointsThreadIdReplayPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ForkCheckpointCheckpointsThreadIdForkPostData = {
    body: ForkRequest;
    path: {
        /**
         * Thread Id
         */
        thread_id: string;
    };
    query?: never;
    url: '/checkpoints/{thread_id}/fork';
};

export type ForkCheckpointCheckpointsThreadIdForkPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ForkCheckpointCheckpointsThreadIdForkPostError = ForkCheckpointCheckpointsThreadIdForkPostErrors[keyof ForkCheckpointCheckpointsThreadIdForkPostErrors];

export type ForkCheckpointCheckpointsThreadIdForkPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListDirectoryEndpointApiFilesListGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Path
         *
         * 相对于根目录的路径，空字符串表示根目录
         */
        path?: string;
    };
    url: '/api/files/list';
};

export type ListDirectoryEndpointApiFilesListGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListDirectoryEndpointApiFilesListGetError = ListDirectoryEndpointApiFilesListGetErrors[keyof ListDirectoryEndpointApiFilesListGetErrors];

export type ListDirectoryEndpointApiFilesListGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetFileEndpointApiFilesFileGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Path
         *
         * 相对于根目录的文件路径
         */
        path: string;
    };
    url: '/api/files/file';
};

export type GetFileEndpointApiFilesFileGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetFileEndpointApiFilesFileGetError = GetFileEndpointApiFilesFileGetErrors[keyof GetFileEndpointApiFilesFileGetErrors];

export type GetFileEndpointApiFilesFileGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ReadFileEndpointApiFilesReadGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Path
         *
         * 相对于根目录的文件路径
         */
        path: string;
    };
    url: '/api/files/read';
};

export type ReadFileEndpointApiFilesReadGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadFileEndpointApiFilesReadGetError = ReadFileEndpointApiFilesReadGetErrors[keyof ReadFileEndpointApiFilesReadGetErrors];

export type ReadFileEndpointApiFilesReadGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type SearchFilesEndpointApiFilesSearchGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Q
         *
         * 搜索关键词
         */
        q: string;
    };
    url: '/api/files/search';
};

export type SearchFilesEndpointApiFilesSearchGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchFilesEndpointApiFilesSearchGetError = SearchFilesEndpointApiFilesSearchGetErrors[keyof SearchFilesEndpointApiFilesSearchGetErrors];

export type SearchFilesEndpointApiFilesSearchGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateFileEndpointApiFilesCreateFilePostData = {
    body: CreateFileRequest;
    path?: never;
    query?: never;
    url: '/api/files/create-file';
};

export type CreateFileEndpointApiFilesCreateFilePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateFileEndpointApiFilesCreateFilePostError = CreateFileEndpointApiFilesCreateFilePostErrors[keyof CreateFileEndpointApiFilesCreateFilePostErrors];

export type CreateFileEndpointApiFilesCreateFilePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateDirectoryEndpointApiFilesCreateDirectoryPostData = {
    body: CreateDirectoryRequest;
    path?: never;
    query?: never;
    url: '/api/files/create-directory';
};

export type CreateDirectoryEndpointApiFilesCreateDirectoryPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateDirectoryEndpointApiFilesCreateDirectoryPostError = CreateDirectoryEndpointApiFilesCreateDirectoryPostErrors[keyof CreateDirectoryEndpointApiFilesCreateDirectoryPostErrors];

export type CreateDirectoryEndpointApiFilesCreateDirectoryPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UploadFileEndpointApiFilesUploadPostData = {
    body: BodyUploadFileEndpointApiFilesUploadPost;
    path?: never;
    query: {
        /**
         * Path
         *
         * 目标相对路径（含文件名），如 docs/readme.md
         */
        path: string;
    };
    url: '/api/files/upload';
};

export type UploadFileEndpointApiFilesUploadPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadFileEndpointApiFilesUploadPostError = UploadFileEndpointApiFilesUploadPostErrors[keyof UploadFileEndpointApiFilesUploadPostErrors];

export type UploadFileEndpointApiFilesUploadPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RenameEndpointApiFilesRenamePutData = {
    body: RenameRequest;
    path?: never;
    query?: never;
    url: '/api/files/rename';
};

export type RenameEndpointApiFilesRenamePutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RenameEndpointApiFilesRenamePutError = RenameEndpointApiFilesRenamePutErrors[keyof RenameEndpointApiFilesRenamePutErrors];

export type RenameEndpointApiFilesRenamePutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type MoveEndpointApiFilesMovePutData = {
    body: MoveRequest;
    path?: never;
    query?: never;
    url: '/api/files/move';
};

export type MoveEndpointApiFilesMovePutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MoveEndpointApiFilesMovePutError = MoveEndpointApiFilesMovePutErrors[keyof MoveEndpointApiFilesMovePutErrors];

export type MoveEndpointApiFilesMovePutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ModifyFileEndpointApiFilesModifyPutData = {
    body: ModifyFileRequest;
    path?: never;
    query?: never;
    url: '/api/files/modify';
};

export type ModifyFileEndpointApiFilesModifyPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ModifyFileEndpointApiFilesModifyPutError = ModifyFileEndpointApiFilesModifyPutErrors[keyof ModifyFileEndpointApiFilesModifyPutErrors];

export type ModifyFileEndpointApiFilesModifyPutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteEndpointApiFilesDeleteDeleteData = {
    body: DeleteRequest;
    path?: never;
    query?: never;
    url: '/api/files/delete';
};

export type DeleteEndpointApiFilesDeleteDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteEndpointApiFilesDeleteDeleteError = DeleteEndpointApiFilesDeleteDeleteErrors[keyof DeleteEndpointApiFilesDeleteDeleteErrors];

export type DeleteEndpointApiFilesDeleteDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ReadModelConfigEndpointSettingsModelConfigReadGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Path
         *
         * 配置文件标识
         */
        path: string;
    };
    url: '/settings/model-config/read';
};

export type ReadModelConfigEndpointSettingsModelConfigReadGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadModelConfigEndpointSettingsModelConfigReadGetError = ReadModelConfigEndpointSettingsModelConfigReadGetErrors[keyof ReadModelConfigEndpointSettingsModelConfigReadGetErrors];

export type ReadModelConfigEndpointSettingsModelConfigReadGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type WriteModelConfigEndpointSettingsModelConfigWritePutData = {
    body: ModifyFileRequest;
    path?: never;
    query?: never;
    url: '/settings/model-config/write';
};

export type WriteModelConfigEndpointSettingsModelConfigWritePutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type WriteModelConfigEndpointSettingsModelConfigWritePutError = WriteModelConfigEndpointSettingsModelConfigWritePutErrors[keyof WriteModelConfigEndpointSettingsModelConfigWritePutErrors];

export type WriteModelConfigEndpointSettingsModelConfigWritePutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetSkillsSettingsSkillsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/settings/skills';
};

export type GetSkillsSettingsSkillsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpdateSkillsSettingsSkillsPutData = {
    body: SkillsUpdateRequest;
    path?: never;
    query?: never;
    url: '/settings/skills';
};

export type UpdateSkillsSettingsSkillsPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateSkillsSettingsSkillsPutError = UpdateSkillsSettingsSkillsPutErrors[keyof UpdateSkillsSettingsSkillsPutErrors];

export type UpdateSkillsSettingsSkillsPutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RebuildSettingsRebuildPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/settings/rebuild';
};

export type RebuildSettingsRebuildPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListDirectoryEndpointSettingsMemoryAndSkillListGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Type
         *
         * 文件类型: 'memory'=记忆库, 'skills'=技能库
         */
        type: 'memory' | 'skills';
        /**
         * Path
         *
         * 相对于根目录的路径，空字符串表示根目录
         */
        path?: string;
    };
    url: '/settings/memory-and-skill/list';
};

export type ListDirectoryEndpointSettingsMemoryAndSkillListGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListDirectoryEndpointSettingsMemoryAndSkillListGetError = ListDirectoryEndpointSettingsMemoryAndSkillListGetErrors[keyof ListDirectoryEndpointSettingsMemoryAndSkillListGetErrors];

export type ListDirectoryEndpointSettingsMemoryAndSkillListGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetFileEndpointSettingsMemoryAndSkillFileGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Type
         *
         * 文件类型: 'memory'=记忆库, 'skills'=技能库
         */
        type: 'memory' | 'skills';
        /**
         * Path
         *
         * 相对于根目录的文件路径
         */
        path: string;
    };
    url: '/settings/memory-and-skill/file';
};

export type GetFileEndpointSettingsMemoryAndSkillFileGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetFileEndpointSettingsMemoryAndSkillFileGetError = GetFileEndpointSettingsMemoryAndSkillFileGetErrors[keyof GetFileEndpointSettingsMemoryAndSkillFileGetErrors];

export type GetFileEndpointSettingsMemoryAndSkillFileGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ReadFileEndpointSettingsMemoryAndSkillReadGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Type
         *
         * 文件类型: 'memory'=记忆库, 'skills'=技能库
         */
        type: 'memory' | 'skills';
        /**
         * Path
         *
         * 相对于根目录的文件路径
         */
        path: string;
    };
    url: '/settings/memory-and-skill/read';
};

export type ReadFileEndpointSettingsMemoryAndSkillReadGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadFileEndpointSettingsMemoryAndSkillReadGetError = ReadFileEndpointSettingsMemoryAndSkillReadGetErrors[keyof ReadFileEndpointSettingsMemoryAndSkillReadGetErrors];

export type ReadFileEndpointSettingsMemoryAndSkillReadGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type SearchFilesEndpointSettingsMemoryAndSkillSearchGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Type
         *
         * 文件类型: 'memory'=记忆库, 'skills'=技能库
         */
        type: 'memory' | 'skills';
        /**
         * Q
         *
         * 搜索关键词
         */
        q: string;
    };
    url: '/settings/memory-and-skill/search';
};

export type SearchFilesEndpointSettingsMemoryAndSkillSearchGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchFilesEndpointSettingsMemoryAndSkillSearchGetError = SearchFilesEndpointSettingsMemoryAndSkillSearchGetErrors[keyof SearchFilesEndpointSettingsMemoryAndSkillSearchGetErrors];

export type SearchFilesEndpointSettingsMemoryAndSkillSearchGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateFileEndpointSettingsMemoryAndSkillCreateFilePostData = {
    body: CreateFileRequest;
    path?: never;
    query: {
        /**
         * Type
         *
         * 文件类型: 'memory'=记忆库, 'skills'=技能库
         */
        type: 'memory' | 'skills';
    };
    url: '/settings/memory-and-skill/create-file';
};

export type CreateFileEndpointSettingsMemoryAndSkillCreateFilePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateFileEndpointSettingsMemoryAndSkillCreateFilePostError = CreateFileEndpointSettingsMemoryAndSkillCreateFilePostErrors[keyof CreateFileEndpointSettingsMemoryAndSkillCreateFilePostErrors];

export type CreateFileEndpointSettingsMemoryAndSkillCreateFilePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateDirectoryEndpointSettingsMemoryAndSkillCreateDirectoryPostData = {
    body: CreateDirectoryRequest;
    path?: never;
    query: {
        /**
         * Type
         *
         * 文件类型: 'memory'=记忆库, 'skills'=技能库
         */
        type: 'memory' | 'skills';
    };
    url: '/settings/memory-and-skill/create-directory';
};

export type CreateDirectoryEndpointSettingsMemoryAndSkillCreateDirectoryPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateDirectoryEndpointSettingsMemoryAndSkillCreateDirectoryPostError = CreateDirectoryEndpointSettingsMemoryAndSkillCreateDirectoryPostErrors[keyof CreateDirectoryEndpointSettingsMemoryAndSkillCreateDirectoryPostErrors];

export type CreateDirectoryEndpointSettingsMemoryAndSkillCreateDirectoryPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UploadFileEndpointSettingsMemoryAndSkillUploadPostData = {
    body: BodyUploadFileEndpointSettingsMemoryAndSkillUploadPost;
    path?: never;
    query: {
        /**
         * Type
         *
         * 文件类型: 'memory'=记忆库, 'skills'=技能库
         */
        type: 'memory' | 'skills';
        /**
         * Path
         *
         * 目标相对路径（含文件名），如 docs/readme.md
         */
        path: string;
    };
    url: '/settings/memory-and-skill/upload';
};

export type UploadFileEndpointSettingsMemoryAndSkillUploadPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadFileEndpointSettingsMemoryAndSkillUploadPostError = UploadFileEndpointSettingsMemoryAndSkillUploadPostErrors[keyof UploadFileEndpointSettingsMemoryAndSkillUploadPostErrors];

export type UploadFileEndpointSettingsMemoryAndSkillUploadPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RenameEndpointSettingsMemoryAndSkillRenamePutData = {
    body: RenameRequest;
    path?: never;
    query: {
        /**
         * Type
         *
         * 文件类型: 'memory'=记忆库, 'skills'=技能库
         */
        type: 'memory' | 'skills';
    };
    url: '/settings/memory-and-skill/rename';
};

export type RenameEndpointSettingsMemoryAndSkillRenamePutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RenameEndpointSettingsMemoryAndSkillRenamePutError = RenameEndpointSettingsMemoryAndSkillRenamePutErrors[keyof RenameEndpointSettingsMemoryAndSkillRenamePutErrors];

export type RenameEndpointSettingsMemoryAndSkillRenamePutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type MoveEndpointSettingsMemoryAndSkillMovePutData = {
    body: MoveRequest;
    path?: never;
    query: {
        /**
         * Type
         *
         * 文件类型: 'memory'=记忆库, 'skills'=技能库
         */
        type: 'memory' | 'skills';
    };
    url: '/settings/memory-and-skill/move';
};

export type MoveEndpointSettingsMemoryAndSkillMovePutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MoveEndpointSettingsMemoryAndSkillMovePutError = MoveEndpointSettingsMemoryAndSkillMovePutErrors[keyof MoveEndpointSettingsMemoryAndSkillMovePutErrors];

export type MoveEndpointSettingsMemoryAndSkillMovePutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ModifyFileEndpointSettingsMemoryAndSkillModifyPutData = {
    body: ModifyFileRequest;
    path?: never;
    query: {
        /**
         * Type
         *
         * 文件类型: 'memory'=记忆库, 'skills'=技能库
         */
        type: 'memory' | 'skills';
    };
    url: '/settings/memory-and-skill/modify';
};

export type ModifyFileEndpointSettingsMemoryAndSkillModifyPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ModifyFileEndpointSettingsMemoryAndSkillModifyPutError = ModifyFileEndpointSettingsMemoryAndSkillModifyPutErrors[keyof ModifyFileEndpointSettingsMemoryAndSkillModifyPutErrors];

export type ModifyFileEndpointSettingsMemoryAndSkillModifyPutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteEndpointSettingsMemoryAndSkillDeleteDeleteData = {
    body: DeleteRequest;
    path?: never;
    query: {
        /**
         * Type
         *
         * 文件类型: 'memory'=记忆库, 'skills'=技能库
         */
        type: 'memory' | 'skills';
    };
    url: '/settings/memory-and-skill/delete';
};

export type DeleteEndpointSettingsMemoryAndSkillDeleteDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteEndpointSettingsMemoryAndSkillDeleteDeleteError = DeleteEndpointSettingsMemoryAndSkillDeleteDeleteErrors[keyof DeleteEndpointSettingsMemoryAndSkillDeleteDeleteErrors];

export type DeleteEndpointSettingsMemoryAndSkillDeleteDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ProcessRagEndpointApiRagProcessPostData = {
    body: RagProcessRequest;
    path?: never;
    query?: never;
    url: '/api/rag/process';
};

export type ProcessRagEndpointApiRagProcessPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProcessRagEndpointApiRagProcessPostError = ProcessRagEndpointApiRagProcessPostErrors[keyof ProcessRagEndpointApiRagProcessPostErrors];

export type ProcessRagEndpointApiRagProcessPostResponses = {
    /**
     * Successful Response
     */
    200: RagProcessResponse;
};

export type ProcessRagEndpointApiRagProcessPostResponse = ProcessRagEndpointApiRagProcessPostResponses[keyof ProcessRagEndpointApiRagProcessPostResponses];

export type ProcessUploadEndpointApiRagProcessUploadPostData = {
    body: BodyProcessUploadEndpointApiRagProcessUploadPost;
    path?: never;
    query?: {
        /**
         * Preview Only
         *
         * 仅预览分块而不入库
         */
        preview_only?: boolean;
    };
    url: '/api/rag/process/upload';
};

export type ProcessUploadEndpointApiRagProcessUploadPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProcessUploadEndpointApiRagProcessUploadPostError = ProcessUploadEndpointApiRagProcessUploadPostErrors[keyof ProcessUploadEndpointApiRagProcessUploadPostErrors];

export type ProcessUploadEndpointApiRagProcessUploadPostResponses = {
    /**
     * Successful Response
     */
    200: RagProcessResponse;
};

export type ProcessUploadEndpointApiRagProcessUploadPostResponse = ProcessUploadEndpointApiRagProcessUploadPostResponses[keyof ProcessUploadEndpointApiRagProcessUploadPostResponses];

export type DeleteRagEndpointApiRagDeletePostData = {
    body: RagDeleteRequest;
    path?: never;
    query?: never;
    url: '/api/rag/delete';
};

export type DeleteRagEndpointApiRagDeletePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteRagEndpointApiRagDeletePostError = DeleteRagEndpointApiRagDeletePostErrors[keyof DeleteRagEndpointApiRagDeletePostErrors];

export type DeleteRagEndpointApiRagDeletePostResponses = {
    /**
     * Successful Response
     */
    200: RagDeleteResponse;
};

export type DeleteRagEndpointApiRagDeletePostResponse = DeleteRagEndpointApiRagDeletePostResponses[keyof DeleteRagEndpointApiRagDeletePostResponses];

export type HealthRagEndpointApiRagHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/rag/health';
};

export type HealthRagEndpointApiRagHealthGetResponses = {
    /**
     * Successful Response
     */
    200: RagHealthResponse;
};

export type HealthRagEndpointApiRagHealthGetResponse = HealthRagEndpointApiRagHealthGetResponses[keyof HealthRagEndpointApiRagHealthGetResponses];

export type GetRagConfigEndpointApiRagConfigGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/rag/config';
};

export type GetRagConfigEndpointApiRagConfigGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpdateRagConfigEndpointApiRagConfigPutData = {
    body: RagFullConfigModel;
    path?: never;
    query?: never;
    url: '/api/rag/config';
};

export type UpdateRagConfigEndpointApiRagConfigPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateRagConfigEndpointApiRagConfigPutError = UpdateRagConfigEndpointApiRagConfigPutErrors[keyof UpdateRagConfigEndpointApiRagConfigPutErrors];

export type UpdateRagConfigEndpointApiRagConfigPutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListCollectionsEndpointApiRagCollectionsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/rag/collections';
};

export type ListCollectionsEndpointApiRagCollectionsGetResponses = {
    /**
     * Successful Response
     */
    200: CollectionListResponse;
};

export type ListCollectionsEndpointApiRagCollectionsGetResponse = ListCollectionsEndpointApiRagCollectionsGetResponses[keyof ListCollectionsEndpointApiRagCollectionsGetResponses];

export type CollectionStatsEndpointApiRagCollectionCollectionNameStatsGetData = {
    body?: never;
    path: {
        /**
         * Collection Name
         */
        collection_name: string;
    };
    query?: {
        /**
         * Sample Limit
         *
         * 统计采样上限
         */
        sample_limit?: number;
    };
    url: '/api/rag/collection/{collection_name}/stats';
};

export type CollectionStatsEndpointApiRagCollectionCollectionNameStatsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CollectionStatsEndpointApiRagCollectionCollectionNameStatsGetError = CollectionStatsEndpointApiRagCollectionCollectionNameStatsGetErrors[keyof CollectionStatsEndpointApiRagCollectionCollectionNameStatsGetErrors];

export type CollectionStatsEndpointApiRagCollectionCollectionNameStatsGetResponses = {
    /**
     * Successful Response
     */
    200: CollectionStatsResponse;
};

export type CollectionStatsEndpointApiRagCollectionCollectionNameStatsGetResponse = CollectionStatsEndpointApiRagCollectionCollectionNameStatsGetResponses[keyof CollectionStatsEndpointApiRagCollectionCollectionNameStatsGetResponses];

export type CollectionDocumentsEndpointApiRagCollectionCollectionNameDocumentsGetData = {
    body?: never;
    path: {
        /**
         * Collection Name
         */
        collection_name: string;
    };
    query?: {
        /**
         * Page
         *
         * 页码
         */
        page?: number;
        /**
         * Page Size
         *
         * 每页条数
         */
        page_size?: number;
    };
    url: '/api/rag/collection/{collection_name}/documents';
};

export type CollectionDocumentsEndpointApiRagCollectionCollectionNameDocumentsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CollectionDocumentsEndpointApiRagCollectionCollectionNameDocumentsGetError = CollectionDocumentsEndpointApiRagCollectionCollectionNameDocumentsGetErrors[keyof CollectionDocumentsEndpointApiRagCollectionCollectionNameDocumentsGetErrors];

export type CollectionDocumentsEndpointApiRagCollectionCollectionNameDocumentsGetResponses = {
    /**
     * Successful Response
     */
    200: CollectionDocumentsResponse;
};

export type CollectionDocumentsEndpointApiRagCollectionCollectionNameDocumentsGetResponse = CollectionDocumentsEndpointApiRagCollectionCollectionNameDocumentsGetResponses[keyof CollectionDocumentsEndpointApiRagCollectionCollectionNameDocumentsGetResponses];

export type DeleteCollectionDocsEndpointApiRagCollectionCollectionNameDeleteDocsPostData = {
    body: DeleteDocsRequest;
    path: {
        /**
         * Collection Name
         */
        collection_name: string;
    };
    query?: never;
    url: '/api/rag/collection/{collection_name}/delete-docs';
};

export type DeleteCollectionDocsEndpointApiRagCollectionCollectionNameDeleteDocsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteCollectionDocsEndpointApiRagCollectionCollectionNameDeleteDocsPostError = DeleteCollectionDocsEndpointApiRagCollectionCollectionNameDeleteDocsPostErrors[keyof DeleteCollectionDocsEndpointApiRagCollectionCollectionNameDeleteDocsPostErrors];

export type DeleteCollectionDocsEndpointApiRagCollectionCollectionNameDeleteDocsPostResponses = {
    /**
     * Successful Response
     */
    200: DeleteDocsResponse;
};

export type DeleteCollectionDocsEndpointApiRagCollectionCollectionNameDeleteDocsPostResponse = DeleteCollectionDocsEndpointApiRagCollectionCollectionNameDeleteDocsPostResponses[keyof DeleteCollectionDocsEndpointApiRagCollectionCollectionNameDeleteDocsPostResponses];

export type ClearCollectionEndpointApiRagCollectionCollectionNameClearPostData = {
    body?: never;
    path: {
        /**
         * Collection Name
         */
        collection_name: string;
    };
    query?: never;
    url: '/api/rag/collection/{collection_name}/clear';
};

export type ClearCollectionEndpointApiRagCollectionCollectionNameClearPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ClearCollectionEndpointApiRagCollectionCollectionNameClearPostError = ClearCollectionEndpointApiRagCollectionCollectionNameClearPostErrors[keyof ClearCollectionEndpointApiRagCollectionCollectionNameClearPostErrors];

export type ClearCollectionEndpointApiRagCollectionCollectionNameClearPostResponses = {
    /**
     * Successful Response
     */
    200: ClearCollectionResponse;
};

export type ClearCollectionEndpointApiRagCollectionCollectionNameClearPostResponse = ClearCollectionEndpointApiRagCollectionCollectionNameClearPostResponses[keyof ClearCollectionEndpointApiRagCollectionCollectionNameClearPostResponses];

export type DeleteCollectionEndpointApiRagCollectionCollectionNameDeleteData = {
    body?: never;
    path: {
        /**
         * Collection Name
         */
        collection_name: string;
    };
    query?: never;
    url: '/api/rag/collection/{collection_name}';
};

export type DeleteCollectionEndpointApiRagCollectionCollectionNameDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteCollectionEndpointApiRagCollectionCollectionNameDeleteError = DeleteCollectionEndpointApiRagCollectionCollectionNameDeleteErrors[keyof DeleteCollectionEndpointApiRagCollectionCollectionNameDeleteErrors];

export type DeleteCollectionEndpointApiRagCollectionCollectionNameDeleteResponses = {
    /**
     * Successful Response
     */
    200: DeleteCollectionResponse;
};

export type DeleteCollectionEndpointApiRagCollectionCollectionNameDeleteResponse = DeleteCollectionEndpointApiRagCollectionCollectionNameDeleteResponses[keyof DeleteCollectionEndpointApiRagCollectionCollectionNameDeleteResponses];
